INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Walmart', 'WalMart Stores, Inc. ˈwɔːlmɑːrt, doing business as Walmart, is an American multinational retailing corporation that operates as a chain of hypermarkets, discount department stores, and grocery stores. Headquartered in Bentonville, Arkansas, the company was founded by Sam Walton in 1962 and incorporated on October 31, 1969. As of January 31, 2017, Walmart has 11,695 stores and clubs in 28160;countries, under a total of 63160;banners. The company operates under the name Walmart in the United States and Canada. It operates as Walmart de México y Centroamérica in Mexico and Central America, as Asda in the United Kingdom, as the Seiyu Group in Japan, and as Best Price in India. It has wholly owned operations in Argentina, Brazil, and Canada. It also owns and operates the Sams Club retail warehouses.', 'United States, Bentonville, Arkansas', 'http://corporate.walmart.com/#https://www.walmart.com/', 1);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 1, ' p { font-size: 21px; line-height: 1.2; font-weight: 500; } .pv3-video .pv3-video-pagination .slick-', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('State Grid Corporation of China', 'State Grid Corporation of China SGCC; Chinese 国家电网公司; pinyin Guójiā Diànwǎng Gōngsī is the largest electric utility company in the world. It is stateowned and transmits and distributes power in China and in overseas markets. The power distributor is headquartered in Xicheng District, Beijing and manages distribution from four regional subsidiaries.', 'Beijing, Shu Yinbiao', 'http://www.sgcc.com.cn/ywlm/default.shtml', 2);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 2, 'writeln ("")\r\ndocument.writeln ("")\r\ndocument.writeln ("")\r\ndocument.writeln ("html,body{margi', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Samsung', 'Samsung Group Hangul160;삼성; Hanja160;三星; Korean pronunciation160; is a South Korean multinational conglomerate headquartered in Samsung Town, Seoul. It comprises numerous affiliated businesses, most of them united under the Samsung brand, and is the largest South Korean chaebol business conglomerate.', 'Suwon, Kwon Ohhyun', 'http://Samsung.com', 3);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 3, ' OK Închideţi fereastra pop-up strat Nu mai afişa Accesaţi Închideţi fereastra pop-up strat Noul Gal', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('China National Petroleum Corporation', 'China National Petroleum Corporation CNPC simplified Chinese 中国石油天然气集团公司; traditional Chinese 中國石油天然氣集團公司; pinyin Zhōngguó Shíyóu Tiānránqì Jítuán Gōngsī is a Chinese stateowned oil and gas corporation and the largest integrated energy company in China. Its headquarters are in Dongcheng District, Beijing. CNPC was ranked the third in 2016 Fortune Global 500.', 'Wang Yilin, ', 'http://www.cnpc.com.cn/en/', 4);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 4, '> 03 01, 2017 CNPC and CASIC sign agreement to deepen strategic cooperation 02 20, 2017 CNPC is awar', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Sinopec Group', 'China Petrochemical Corporation Chinese 中国石油化工集团公司 or Sinopec Group is Asias largest oil refining and petrochemical enterprise, administered by SASAC for the State Council of the Peoples Republic of China. It is headquartered at Chaoyangmenwai in Beijing, across the road from the headquarters of fellow stateowned oil company and competitor CNOOC Group.', 'Wang Yupu, ', 'http://www.sinopecgroup.com/group/en/', 5);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 5, ' Sinopec Lubricants(Australia) LPG Lubricants Automotive lubricants Human resources Oil Products Ser', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Royal Dutch Shell', 'Royal Dutch Shell plc LSE160;RDSA, RDSB, commonly known as Shell, is an AngloDutch multinational oil and gas company headquartered in the Netherlands and incorporated in the United Kingdom. It is one of the six oil and gas supermajors and the fifthlargest company in the world measured by 201516 revenues and the largest based in Europe. Shell was first in the 2013 Fortune Global 500 list of the worlds largest companies; in that year its revenues were equivalent to 84 of the Netherlands 556 billion GDP.', 'Ben van Beurden, ', 'http://www.shell.com', 6);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 6, ' What customers say Shell Global Solutions Back Shell Global Solutions About Shell Global Solutions ', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('ExxonMobil', 'Exxon Mobil Corporation is an American multinational oil and gas corporation headquartered in Irving, Texas. It is the largest direct descendant of John D. Rockefellers Standard Oil Company, and was formed on November 30, 1999 by the merger of Exxon formerly Standard Oil Company of New Jersey and Mobil formerly the Standard Oil Company of New York.', 'Darren Woods, ', 'http://www.exxonmobil.com', 7);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 7, ' Russia ExxonMobil Russian Corporate overview The Netherlands ExxonMobil English French Dutch Europe', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Volkswagen Group', 'Volkswagen Group pronounced , or Volkswagen Aktiengesellschaft pronounced , shortly VW AG, is a German multinational automotive manufacturing company headquartered in Wolfsburg, Lower Saxony, Germany. It designs, manufactures and distributes passenger and commercial vehicles, motorcycles, engines, and turbomachinery and offers related services including financing, leasing and fleet management. In 2016, it was the largest automaker in the world with sales 10.3 million units. It has maintained the largest market share in Europe for over two decades. It ranked seventh in the 2016 Fortune Global 500 list of the worlds largest companies.', 'Matthias Müller businessman, ', 'http://volkswagenag.com', 8);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 8, ' Read here our exciting and brand new topics of the week. &#xe028; To all topics Stories To all topi', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Toyota', 'Toyota Motor Corporation Japanese トヨタ自動車株式会社, Hepburn Toyota Jidōsha KK, IPA160;, tɔɪˈoʊtə is a Japanese automotive manufacturer headquartered in Toyota, Aichi, Japan. In March 2014, the multinational corporation consisted of 338,875 employees worldwide and, as of February 2016, was the 13thlargest company in the world by revenue. Toyota was the largest automobile manufacturer in 2012 by production ahead of the Volkswagen Group and General Motors. In July of that year, the company reported the production of its 200millionth vehicle. Toyota is the worlds first automobile manufacturer to produce more than 10 million vehicles per year. It did so in 2012 according to OICA, and in 2013, according to company data. As of July 2014, Toyota was the largest listed company in Japan by market capitalization worth more than twice as much as 2ranked SoftBank and by revenue.', 'Akio Toyoda, ', 'http://toyota-global.com', 9);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 9, ' Back Forward Design Experience Performance Inside Toyota {{#if title}} {{{title}}} {{/if}} {{#if de', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Apple Inc.', 'Coordinates 371955N 1220152W  37.33182N 122.03118W  37.33182; 122.03118', 'Cupertino, California, Tim Cook', 'https://www.apple.com', 10);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 10, ' Close Menu Find a Store Genius Bar Workshops and Learning Youth Programs Apple Store App Refurbishe', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('BP', 'BP P.L.C., also referred to by its former name, British Petroleum, is a British multinational oil and gas company headquartered in London, England. It is one of the worlds seven oil and gas supermajors, whose performance in 2012 made it the worlds sixthlargest oil and gas company, the sixthlargest energy company by market capitalization and the company with the worlds fifthlargest revenue turnover. It is a vertically integrated company operating in all areas of the oil and gas industry, including exploration and production, refining, distribution and marketing, petrochemicals, power generation and trading. It also has renewable energy interests in biofuels and wind power.', 'London, Bob Dudley', 'http://www.bp.com/', 11);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 11, ' Air quality Water Oil spill preparedness Biodiversity and sensitive areas Environment: case studies', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Berkshire Hathaway', 'Berkshire Hathaway Inc. is an American multinational conglomerate holding company headquartered in Omaha, Nebraska, United States. The company wholly owns GEICO, BNSF Railway, Lubrizol, Dairy Queen, Fruit of the Loom, Helzberg Diamonds, FlightSafety International, Pampered Chef, and NetJets, and also owns 43.63 of the Kraft Heinz Company, an undisclosed percentage of Mars, Incorporated, and significant minority holdings in American Express, The CocaCola Company, Wells Fargo, IBM and Restaurant Brands International. Berkshire Hathaway averaged an annual growth in book value of 19.7 to its shareholders for the last 49 years compared to 9.8 from the Samp;P 500 with dividends included for the same period, while employing large amounts of capital, and minimal debt.', 'Omaha, Nebraska, Warren Buffett', 'http://berkshirehathaway.com', 12);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 12, ' Shareholders Updated February 25, 2017 Special Letters From Warren & Charlie RE:Past, Present and F', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('McKesson Corporation', 'McKesson Corporation is an American company distributing pharmaceuticals at a retail sale level and providing health information technology, medical supplies, and care management tools. The company had sales of 122 billion in 2012.', 'San Francisco, John Hammergren', 'http://www.mckesson.com', 13);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 13, ' Popular Solutions Medical Supplies Equipment For Providers | For Pharmacies Health Mart Retail Phar', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Glencore', 'Glencore plc an acronym for Global Energy Commodity Resources is an AngloSwiss multinational commodity trading and mining company with headquarters in Baar, Switzerland, and a registered office in Saint Helier, Jersey. The current company was created through a merger of Glencore with Xstrata on 2 May 2013. As of 2015, it ranked tenth in the Fortune Global 500 list of the worlds largest companies. It is the worlds thirdlargest family business.', 'Baar, Switzerland, Ivan Glasenberg', 'http://www.glencore.com/', 14);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 14, 'lid;border-width:6px 5.5px 0;border-color:#00768b transparent transparent;z-index:100}.nav-main__lis', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Industrial and Commercial Bank of China', 'Industrial and Commercial Bank of China Limited ICBC; simplified Chinese 中国工商银行; traditional Chinese 中國工商銀行; pinyin Zhōngguó Gōngshāng Yínháng, more commonly just 工行 Gōngháng is a Chinese multinational banking company, and the largest bank in the world by total assets and market capitalization as of February 2017. It is one of Chinas Big Four stateowned commercial banks the other three being the Bank of China, Agricultural Bank of China, and China Construction Bank. It was founded as a limited company on January 1, 1984. As of June 2015, it had assets worth US3.616 trillion. Generally considered the largest bank and public company in the world by assets; it is the first Chinese bank to achieve such a feat. It ranks number 1 in The Bankers Top 1000 World Banks ranking, and first on the Forbes Global 2000 list of the worlds biggest public companies.', 'Beijing, Yi Huiman', 'http://www.icbc.com.cn', 15);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 15, 'C/%E6%B5%B7%E5%A4%96%E5%88%86%E8%A1%8C/%E5%8D%B0%E5%B0%BC%E7%BD%91%E7%AB%99/it/default.htm";\r\n }\r', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Daimler AG', 'Daimler AG German pronunciation 160; listen is a German multinational automotive corporation. Daimler AG is headquartered in Stuttgart, BadenWürttemberg, Germany. As of 2014, Daimler owns or has shares in a number of car, bus, truck and motorcycle brands including MercedesBenz, MercedesAMG, Smart Automobile, Detroit Diesel, Freightliner, Western Star, Thomas Built Buses, Setra, BharatBenz, Mitsubishi Fuso, MV Agusta as well as shares in Denza, KAMAZ, Beijing Automotive Group. The Maybach brand was closed at the end of 2012, but was revived in April 2015 as MercedesMaybach, an ultra luxury edition of the MercedesBenz SClass. In 2016 Daimler sold 3.0 million vehicles. By unit sales, Daimler is the thirteenthlargest car manufacturer and is the largest truck manufacturer in the world. In addition to automobiles, Daimler manufactures buses and provides financial services through its Daimler Financial Services arm. The company is a component of the Euro Stoxx 50 stock market index.', 'Stuttgart, Dieter Zetsche', 'http://www.daimler.com/en/', 16);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 16, 'ew Vocational training Overview Vocational Training in detail Application Process Technical Trainees', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('United Health', 'UnitedHealth Group Inc. is an American managed health care company based in Minnetonka, Minnesota. It is 6th in the United States on the Fortune 500. UnitedHealth Group offers products and services through two operating businesses, UnitedHealthcare and Optum, both subsidiaries of UnitedHealth Group. Optum is a new business brand of UnitedHealth Group and operating business andBusiness Process Outsourcing BPO services. UnitedHealth Group serves approximately 70 million individuals throughout the United States. In 2015, the company reported an operating income of 11 billion.', 'Minnetonka, Minnesota, Stephen Hemsley', 'http://www.unitedhealthgroup.com', 17);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 17, ' learn more --> Ideas for a modern, high-performing, simpler health care system A more modern, high-', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('CVS Health', 'CVS Health previously CVS Corporation and CVS Caremark Corporation stylized as CVSHealth is an American retail pharmacy and health care company headquartered in Woonsocket, Rhode Island. The company began in 1964 with three partners who grew the venture from a parent company, Mark Steven, Inc., that helped retailers manage their health and beauty aid product lines. The business began as a chain of health and beauty aid stores, but within several years, pharmacies were added. To facilitate growth and expansion, the company joined The Melville Corporation, which managed a string of retail businesses. Following a period of growth in the 1980s and 1990s, CVS Corporation spun off from Melville in 1996, becoming a standalone company trading on the New York Stock Exchange as NYSE160;CVS ', 'Woonsocket, Rhode Island, Larry Merlo', 'http://cvshealth.com', 18);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 18, 'ryOur Business Model Growth Drivers Capital Allocation Long Term Targets Results Center 2015 In Revi', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Exor company', 'Exor N.V. is a leading investment company, controlled by the Agnelli family. It has a capitalization of over US13 billion, with a history of investments running over a century. Its principal investments include Fiat Chrysler Automobiles, CNH Industrial and Ferrari. Resultantly, Exor is first as an economic group in Italy for sales volume, and the 19th in the world.', 'Turin, John Elkann', 'http://www.exor.com/', 19);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 19, ' Select January 2008 February 2008 March 2008 April 2008 May 2008 June 2008 July 2008 August 2008 Se', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('General Motors', 'General Motors Company, commonly known as GM, is an American multinational corporation headquartered in Detroit, Michigan, that designs, manufactures, markets, and distributes vehicles and vehicle parts, and sells financial services. With global headquarters at the Renaissance Center in Detroit, Michigan, United States, GM manufactures cars and trucks in 35 countries. In 2008, 8.35 million GM cars and trucks were sold globally under various brands. Current auto brands are Buick, Cadillac, Chevrolet, GMC, Holden, and Wuling. Former GM automotive brands include McLaughlin, Oakland, Oldsmobile, Pontiac, Hummer, Saab, and Saturn.', 'Mary Barra, ', 'http://www.gm.com/index.html', 20);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 20, ' General Motors | Official Global Site | GM.com MENU Select a Country | Contact Us | Careers | x Can', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Ford Motor Company', 'Coordinates 421855N 831237W  42.315278N 83.210278W  42.315278; 83.210278', 'Mark Fields businessman, ', 'http://www.ford.com/', 21);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 21, ' 2017 Edge from 1 2017 Flex from 1 2017 Explorer from 1 2017 Expedition from 1 2017 Transit Connect ', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('China Construction Bank', 'China Construction Bank Corporation CCB; simplified Chinese 中国建设银行; traditional Chinese 中國建設銀行; pinyin Zhōngguó Jiànshè Yínháng; often abbreviated as 建行; SSE 601939, SEHK160;0939, OTC Pink CICHY is one of the big four banks in the Peoples Republic of China. In 2015 CCB was the 2nd largest bank in the world by market capitalization and 6th largest company in the world. The bank has approximately 13,629 domestic branches. In addition, it maintains overseas branches in Barcelona, Frankfurt, Luxembourg, Hong Kong, Johannesburg, New York City, Seoul, Singapore, Tokyo, Melbourne, Sydney and Auckland, and a wholly owned subsidiary in London. Its total assets reached CN 8.7160;trillion in 2009. Its headquarters is in Xicheng District, Beijing.', 'Beijing, ', 'http://www.ccb.com/en/home/index.html', 22);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 22, ' 中文 1234 var imgProbability=new Array(); imgProbability[0]=\'30\'; imgProbability[1]=\'60\'; imgProb', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('ATamp;T Inc.', 'ATamp;T Inc. is an American multinational telecommunications conglomerate, headquartered at Whitacre Tower in downtown Dallas, Texas. ATamp;T is the second largest provider of mobile telephone services and the largest provider of fixed telephone services in the United States, and also provides broadband subscription television services through DirecTV. ATamp;T is the thirdlargest company in Texas the largest nonoil company, behind only ExxonMobil and ConocoPhillips, and also the largest Dallas company. As of February 2017, ATamp;T is the 12th largest company in the world as measured by a composite of revenues, profits, assets and market value, and the 12th largest nonoil company. ATamp;T is the largest telecommunications company in the world by revenue. As of 2017, it is also the 18thlargest mobile telecom operator in the world, with 135 million mobile customers. ATamp;T was ranked at 4 on the 2017 rankings of the worlds most valuable brands published by Brand Finance.', 'Dallas, Texas, Randall L. Stephenson', 'https://www.att.com/', 23);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 23, ' U-verse TV Support Welcome Center Billing Account Remote Controls Troubleshooting DIRECTV Support W', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Total S.A.', 'Total S.A. French pronunciation160;; English toʊˈtæl or toʊˈtɑːl is a French multinational integrated oil and gas company and one of the seven Supermajor oil companies in the world. Its businesses cover the entire oil and gas chain, from crude oil and natural gas exploration and production to power generation, transportation, refining, petroleum product marketing, and international crude oil and product trading.', 'Courbevoie, Patrick Pouyanné', 'http://www.total.com', 24);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 24, ' Trading and shipping Oil and gas: Matching energy supply and demand Our integrated approach: A comp', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Foxconn', 'Hon Hai Precision Industry Co., Ltd., trading as Foxconn Technology Group, is a Taiwanese multinational electronics contract manufacturing company headquartered in New Taipei City, Taiwan. Foxconn is the worlds largest contract electronics manufacturer, and the thirdlargest information technology company by revenue.', 'Taiwan, Terry Gou', 'http://www.foxconn.com', 25);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 25, ' --> 2017-03-10 Hon Hai announced unaudited consolidated revenue for February 2017 2017-02-10 Hon Ha', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('General Electric', 'General Electric, often abbreviated as GE, is an American multinational conglomerate corporation incorporated in New York, and headquartered in Boston, Massachusetts. As of 2016, the company operates through the following segments Power amp; Water, Oil and Gas, Aviation, Healthcare, Transportation and Capital which cater to the needs of Financial services, Medical devices, Life Sciences, Pharmaceutical, Automotive, Software Development and Engineering industries.', 'Boston, Massachusetts, Jeffrey Immelt', 'http://www.ge.com', 26);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 26, 'evious":"\u00ab Prev","next":"Next \u00bb","close":"Close","maxWidth":"98%","maxHeight":"98%","fixed', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('China State Construction Engineering', 'The China State Construction Engineering Corporation CSCEC Chinese 中国建筑工程总公司 is a Chinese construction company ranked the 3rd largest in the world 1st according to International Construction and the 20th largest general contractor in terms of overseas sales.', 'Beijing, ', 'http://www.cscec.com.cn/', 27);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 27, ' ', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('AmerisourceBergen', 'AmerisourceBergen Corporation is an American drug wholesale company that was formed by the merger of Bergen Brunswig and AmeriSource in 2001. They provide drug distribution and related services designed to reduce costs and improve patient outcomes, distribute a line of brand name and generic pharmaceuticals, overthecounter OTC health care products and home health care supplies and equipment to a wide variety of health care providers located throughout the United States, including acute care hospitals and health systems, independent and chain retail pharmacies, mailorder facilities, physicians, clinics and other alternate site facilities, as well as skilled nursing and assisted living centers. They also provide pharmaceuticals and pharmacy services to longterm care, workers compensation and specialty drug patients.', 'Chesterbrook, Pennsylvania, Steven H. Collis', 'http://www.amerisourcebergen.com/', 28);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 28, ' ', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Agricultural Bank of China', 'Agricultural Bank of China Limited ABC, simplified Chinese 中国农业银行; traditional Chinese 中國農業銀行; pinyin Zhōngguó Nóngyè Yínháng, also known as AgBank or 农行 Nóngháng, is one of the Big Four banks in the Peoples Republic of China. It was founded in 1951, and has its headquarters in Dongcheng District, Beijing. It has branches throughout mainland China, Hong Kong, London, Tokyo, New York, Frankfurt, Sydney, Seoul, and Singapore.', 'Beijing, ', 'http://www.abchina.com', 29);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 29, ' 便捷服务 掌上银行下载 行情数据 图说农行 营业机构查询 在线预约排队 信用卡申请 自助客服 WAP网银登录 K码支付 有手机就行！线上申请，安全便捷 立即注册 > 点击了解 > 大额存单 本息安全', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Verizon Communications', 'Verizon Communications, Inc. 160;listen160;helpinfo vəˈraɪzən vəRYzən simply known as Verizon, stylized as verizon, is a broadband telecommunications company and the largest U.S. wireless communications service provider as of September 2014, and a corporate component of the Dow Jones Industrial Average. The company is based at 1095 Avenue of the Americas in Midtown Manhattan, New York City, but is incorporated in Delaware.', 'New York City, Lowell McAdam', 'http://www.verizon.com/', 30);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 30, '-1 || domainStr.indexOf("www22")>-1)) return true; else return false; } function getDomainStr() { re', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Chevron Corporation', 'Chevron Corporation NYSE160;CVX is an American multinational energy corporation. One of the successor companies of Standard Oil, it is headquartered in San Ramon, California, and active in more than 180 countries. Chevron is engaged in every aspect of the oil, natural gas, and geothermal energy industries, including hydrocarbon exploration and production; refining, marketing and transport; chemicals manufacturing and sales; and power generation. Chevron is one of the worlds largest oil companies; as of 2014, it ranked third in the Fortune 500 list of the top US closely held and public corporations and sixteenth on the Fortune Global 500 list of the top 500 corporations worldwide. It was also one of the Seven Sisters that dominated the global petroleum industry from the mid1940s to the 1970s.', 'San Ramon, California, John S. Watson Chevron', 'http://www.chevron.com/', 31);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 31, ' corporate governance stockholder services stock information financial information archives about ba', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('E.ON', 'E.ON SE marketed with an interpunct as EON is a European holding company based in Essen, North RhineWestphalia, Germany. It runs one of the worlds largest investorowned electric utility service providers. The name comes from the Greek word aeon which means an age. The company is a component of the Euro Stoxx 50 stock market index.', 'Essen, Johannes Teyssen', 'http://www.eon.com', 32);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 32, ' Energienetze Intelligente Energienetze bilden die Infrastruktur für die neue Energiewelt. Unsere in', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('AXA', 'AXA is a French multinational insurance firm headquartered in the 8th arrondissement of Paris that engages in global insurance, investment management, and other financial services.', 'Thomas Buberl, ', 'http://www.axa.com/en', 33);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 33, ' Data virtuosos About us About us Learn more about our mission and vision to protect people by using', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Allianz', 'Allianz SE ˈæliənts ALiənts; German pronunciation 160; listen is a German financial services company headquartered in Munich, Germany. Its core businesses are insurance and asset management. As of 2014, it is the worlds largest insurance company, the largest financial services group and the largest company according to a composite measure by Forbes magazine, as well as the largest financial services company when measured by 2013 revenue. The company is a component of the Euro Stoxx 50 stock market index.', 'Oliver Bäte, ', 'http://www.allianz.com/', 34);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 34, 'estor Relations App FAQ Service & Contact Press News Overview Company Financials Business Studies Co', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Bank of China', 'Not to be confused with the Peoples Bank of China the central bank of the Peoples Republic of China', ', ', 'http://www.boc.cn', 35);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 35, ' 还款指南 开卡指南 使用指南 优惠商户 积分兑换 聪明购 重点推荐 积利金（贵金属积利业务） 积利金，即：贵金属积利业务， 是指中国银行面向个人客户发行的挂钩上海黄金交易所黄金现货的权益资产 分享 ', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Honda', 'Honda Motor Co., Ltd. 本田技研工業株式会社, Honda Giken Kōgyō KK, IPA160;160; listen; ˈhɒndə is a Japanese public multinational conglomerate corporation primarily known as a manufacturer of automobiles, aircraft, motorcycles, and power equipment.', 'Tokyo, Takahiro Hachigo', 'http://world.honda.com/', 36);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 36, ' in Cologne New BF4 BF5 BF6 Honda Marine Debuts New BF4, BF5 and BF6 4-stroke Engines All-new NSX Ho', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Japan Post Holdings', 'Japan Post Holdings Co., Ltd. 日本郵政株式会社, Nippon Yūsei Kabushikigaisha is a Japanese stateowned conglomerate headquartered in Kasumigaseki, Chiyoda, Tokyo. It is mainly engaged in postal and logistics business, financial window business, banking business and life insurance business. The company offers letters and goods transportation services, stamp sales, deposits, loans, and insurance products. There were plans to fully privatize the company, but these have been put on hold. As of 2013, it ranked thirteenth in the Fortune Global 500 list of the worlds largest companies.', 'Tokyo, Masatsugu Nagato', 'http://www.japanpost.jp/en/', 37);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 37, ' Information Main menu ends here. Position:HomeEnglish Home Font Size Changer starts here. Text Size', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Costco', 'Costco Wholesale Corporation is the largest American membershiponly warehouse club that provides a wide selection of merchandise, and as of 2015, was the second largest retailer in the world after Walmart. As of 2016, Costco was the worlds no. 1 retailer of choice and prime beef, organic foods, rotisserie chicken, and wine.', 'Issaquah, Washington, W. Craig Jelinek', 'http://www.costco.com', 38);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 38, ' Denied You don\'t have permission to access "http&#58;&#47;&#47;www&#46;costco&#46;c', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('BNP Paribas', 'BNP Paribas French pronunciation160; is an international banking group with a presence in 75 countries. It is listed on the First Market of Euronext Paris and is included in the CAC 40 index. At 31 December 2016, net income attributable to equity holders was EUR7,702 million.', 'JeanLaurent Bonnafé, ', 'https://group.bnpparibas/en/', 39);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 39, ' Group Entrepreneurship Financial Information History Economy Corporate philanthropy Careers Cinema ', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Fannie Mae', 'The Federal National Mortgage Association FNMA, commonly known as Fannie Mae, is a United States governmentsponsored enterprise GSE and, since 1968, a publicly traded company. Founded in 1938 during the Great Depression as part of the New Deal, the corporations purpose is to expand the secondary mortgage market by securitizing mortgages in the form of mortgagebacked securities MBS, allowing lenders to reinvest their assets into more lending and in effect increasing the number of lenders in the mortgage market by reducing the reliance on locally based savings and loan associations or thrifts. Its brother organization is the Federal Home Loan Mortgage Corporation FHLMC, better known as Freddie Mac.', 'Timothy Mayopoulos, ', 'http://www.fanniemae.com/', 40);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 40, ' ', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Ping An Insurance', 'Ping An Insurance known also as Ping An of China Chinese 中国平安; pinyin Zhōngguó Píng Ān, full name Ping An Insurance Group Company of China, Ltd. is a holding company whose subsidiaries mainly deal with insurance, banking, and financial services. The company was founded in 1988 and has its headquarter in Shenzhen. Ping An literally means safe and well.', ', ', 'http://www.pingan.com', 41);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 41, ' 信用卡 信用卡商城 橙e网 --> 金融旗舰店理财频道 金融旗舰店贷款频道 金融旗舰店信用卡 投资 证券开户 财富宝 期货开户 陆金所 更多我要投资 证券开户 股市直播 基金超市 信托产品预约 信托', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Kroger', 'The Kroger Company, or simply Kroger, is an American retailing company founded by Bernard Kroger in 1883 in Cincinnati, Ohio. It is the United Statess largest supermarket chain by revenue 109.83 billion for fiscal year 2016, the secondlargest general retailer behind Walmart and the twentythird largest company in the United States. Kroger is also the thirdlargest retailer in the world. As of December 2015, Kroger operates, either directly or through its subsidiaries, 2,778 supermarkets and multidepartment stores. Krogers headquarters are in downtown Cincinnati. It maintains markets in 34 states, with store formats that include supermarkets, superstores, department stores, 786 convenience stores, and 326 jewelry stores. Krogerbranded grocery stores are located in the Midwestern and Southern United States. Kroger operates 37 food processing or manufacturing facilities, 1,360 supermarket fuel centers and 2,122 pharmacies.', 'Cincinnati, Rodney McMullen', 'http://www.thekrogerco.com/#https://www.kroger.com/', 42);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 42, ' a"); heroContentItems = $("#hero_content_box > div"); $nav = $("#hero_nav ul li a"); $nav.each(func', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Société Générale', 'Société Générale S.A. is a French multinational banking and financial services company headquartered in Paris. The company is a universal bank and has divisions supporting French Networks, Global Transaction Banking, International Retail Banking, Financial services, Corporate and Investment Banking, Private Banking, Asset Management and Securities Services.', 'Paris, Frédéric Oudéa', 'http://societegenerale.com', 43);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 43, ' Our businesses French Networks Global Transaction Banking International Retail Banking Financial se', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Amazon.com', 'Amazon.com ˈæməzɒn or ˈæməzən, also called Amazon, is an American electronic commerce and cloud computing company that was founded on July 5, 1994 by Jeff Bezos and is based in Seattle, Washington. It is the largest Internetbased retailer in the world by total sales and market capitalization. Amazon.com started as an online bookstore, later diversifying to sell DVDs, Blurays, CDs, video downloadsstreaming, MP3 downloadsstreaming, audiobook downloadsstreaming, software, video games, electronics, apparel, furniture, food, toys and jewelry. The company also produces consumer electronicsnotably, Kindle ereaders, Fire tablets, Fire TV and the Echoand is the worlds largest provider of cloud infrastructure services IaaS and PaaS. Amazon also sells certain lowend products like USB cables under its inhouse brand AmazonBasics.', 'Seattle, Jeff Bezos', 'http://Amazon.com##Website', 44);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 44, ' 503 Service Unavailable Error html, body { padding: 0; margin: 0 } img { border: 0 } #a { backgroun', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('China Mobile', 'China Mobile Communications Corporation is a Chinese stateowned telecommunication company that provides mobile voice and multimedia services through its nationwide mobile telecommunications network. The company is the largest mobile telecommunications company by market capitalization today, and it was named as such in March 2011. China Mobile Limited is listed on both the NYSE and the Hong Kong stock exchange.', 'Beijing, ', 'http://www.10086.cn', 45);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 45, 'de":270,"name":"湖北","href":"http://www.10086.cn/hb","url":"http://shop.10086.cn/mall_270_270.html","', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('SAIC Motor', 'SAIC Motor Corporation Limited informally SAIC, formerly Shanghai Automotive Industry Corporation is a Chinese stateowned automotive design and manufacturing company headquartered in Shanghai, China, with multinational operations. A Fortune Global 100 company and one of the Big Four stateowned Chinese automakers along with Changan Motors, FAW Group, and Dongfeng Motor, the company had the largest production volume of any Chinese automaker in 2014 making more than 4.5 million vehicles. Its manufacturing mix is not wholly consumer offerings, however, with as many as 1,000,000 SAIC passenger vehicles being commercial vans.', 'Shanghai, ', 'http://www.saicmotor.com/english/', 46);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 46, ' var $slide = $(\'#slide\'); var $jslider = $slide.find(\'.slide-list\'); $jslider.length && $jslide', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Walgreens Boots Alliance', 'Walgreens Boots Alliance, Inc. is an American holding company headquartered in Deerfield, Illinois that owns Walgreens, Boots and a number of pharmaceutical manufacturing, wholesale and distribution companies. The company was formed on December 31, 2014 after Walgreens purchased the 55 stake in Switzerlandbased Alliance Boots that it did not already own. Walgreens had previously purchased 45 of the company in 2012 with an option to purchase the remaining shares within three years.', 'Deerfield, Illinois, Stefano Pessina', 'http://walgreensbootsalliance.com', 47);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 47, 'Corporate Social Responsibility Report 2016 Introduction Introduction Our Corporate Social Responsib', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('HewlettPackard', 'Coordinates 372449N 1220842W  37.413579N 122.14508W  37.413579; 122.14508', 'Palo Alto, California, Dion Weisler', 'http://www.hp.com/', 48);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 48, 'oterLaptopuri şi tablete &#160;&#160; Premium Standardowe laptopy Staţii grafice Deta&#351;abile Con', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Assicurazioni Generali', 'Generali Group is the largest insurance company in Italy and third in the world. It has its headquarters in Trieste. In 2010, Assicurazioni Generali Group was the second largest insurance group in the world by revenue after AXA.', 'Trieste, Italy, Philippe Donnet', 'http://www.generali.com', 49);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 49, ' Accessibility Insurance Products with social and environmental value Claim management Best practice', 1);

INSERT INTO COMPANIES (name, description, location, website, certificateId) VALUES ('Cardinal Health', 'Cardinal Health, Inc. is a Fortune 500 health care services company based in Dublin, Ohio. The company specializes in distribution of pharmaceuticals and medical products, serving more than 100,000 locations. The company also manufactures medical and surgical products, including gloves, surgical apparel and fluid management products. In addition, it operates the nations largest network of radiopharmacies. Cardinal Health provides medical products to over 75 percent of hospitals in the United States. In December 2013, it was announced that Cardinal Health would team up with CVS Caremark, which would form the largest generic drug sourcing operation in the United States. The venture was named Red Oak Sourcing and began operations in July 2014.', 'Dublin, Ohio, George S. Barrett', 'http://www.cardinalhealth.com/', 50);
INSERT INTO Certificates (userId, companyId, authority, verified) VALUES (get_student_id(), 50, ' for this opening is found at the bottom of pages/page/body.html. */ --> cardinal.com login Username', 1);

